# Generated by Django 4.0.3 on 2022-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0005_alter_all_lectures_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_lectures',
            name='lecture_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
