# Generated by Django 4.0.3 on 2022-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_alter_all_forums_forum_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_forums',
            name='forum_title',
            field=models.TextField(),
        ),
    ]
