# Generated by Django 4.0.3 on 2022-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_all_tests_options_all_tests_test_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_tests',
            name='files',
            field=models.FileField(null=True, upload_to='test_files/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='test_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='test_instruction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='test_questions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='test_title',
            field=models.CharField(max_length=200),
        ),
    ]
