# Generated by Django 4.0.3 on 2022-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_user_profile_database_edit_once_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_database',
            name='user_profile_photo',
            field=models.FileField(default='C:\\Users\\91844\\OneDrive\\Desktop\\cpp\\codefiles\\vs_coding\\Django\\digischool_iitk-main\\media//image/profile_photo.jpg', null=True, upload_to='image/', verbose_name=''),
        ),
    ]
